# Generated by Django 3.2.13 on 2022-05-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Username', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Password', max_length=255, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('no', models.IntegerField(db_column='No')),
                ('street', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Street', max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='District', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='City', max_length=255, null=True)),
                ('mail', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Mail', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Phone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nameau', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('biography', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Biography', max_length=255, null=True)),
                ('descriptionAut', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Barcode', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Title', max_length=255, null=True)),
                ('language', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Language', max_length=255, null=True)),
                ('numberofpage', models.IntegerField(db_column='NumberOfPage')),
                ('summary', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Summary', max_length=255, null=True)),
                ('descriptionBoo', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookitem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('itemcode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='ItemCode', max_length=255, null=True)),
                ('currentprice', models.FloatField(db_column='CurrentPrice')),
                ('image', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Image', max_length=255, null=True)),
                ('discount', models.FloatField(db_column='Discount')),
                ('descriptionbi', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'bookitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Status', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Note', max_length=255, null=True)),
                ('total', models.FloatField(db_column='Total')),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartBookitem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itemtype', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='ItemType', max_length=255, null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.FloatField(db_column='Price')),
            ],
            options={
                'db_table': 'cart_bookitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nameCat', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('imageCat', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Image', max_length=255, null=True)),
                ('descriptionCat', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Barcode', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('descriptionClo', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clothes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothesitem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nameci', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('clothescode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='ClothesCode', max_length=255, null=True)),
                ('currentprice', models.FloatField(db_column='CurrentPrice')),
                ('imageCI', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Image', max_length=255, null=True)),
                ('discount', models.FloatField(db_column='Discount')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('descriptionCI', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clothesitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Content', max_length=255, null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('rate', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Rate', max_length=255, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ccode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='CCode', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Status', max_length=255, null=True)),
                ('member', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Member', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Firstname', max_length=255, null=True)),
                ('midname', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Midname', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Lastname', max_length=255, null=True)),
            ],
            options={
                'db_table': 'fullname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Barcode', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('warranty', models.IntegerField(db_column='Warranty')),
                ('specification', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Specification', max_length=255, null=True)),
                ('descriptionlap', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
                ('laptopid', models.IntegerField(db_column='LaptopID')),
            ],
            options={
                'db_table': 'laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptopitem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nameli', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('laptopcode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='LaptopCode', max_length=255, null=True)),
                ('currentprice', models.FloatField(db_column='CurrentPrice')),
                ('imageli', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Image', max_length=255, null=True)),
                ('discount', models.FloatField(db_column='Discount')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('descriptionli', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'laptopitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Brand', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Address', max_length=255, null=True)),
                ('descriptionMan', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'manufacture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ordercode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='OrderCode', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Status', max_length=255, null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('updateat', models.DateTimeField(blank=True, db_column='UpdateAt', null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Provider', max_length=255, null=True)),
                ('typePay', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Type', max_length=255, null=True)),
                ('discount', models.FloatField(db_column='Discount')),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Note', max_length=255, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Brand', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Address', max_length=255, null=True)),
                ('descriptionPro', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'producer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('namePub', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Address', max_length=255, null=True)),
                ('descriptionPub', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Provider', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Address', max_length=255, null=True)),
                ('typeShip', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Type', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'shipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nameS', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('size', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Size', max_length=255, null=True)),
                ('color', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Color', max_length=255, null=True)),
                ('material', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Material', max_length=255, null=True)),
                ('descriptionStyle', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'styles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ram', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Ram', max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Cpu', max_length=255, null=True)),
                ('screensize', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='ScreenSize', max_length=255, null=True)),
                ('descriptiontype', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
                ('gpu', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Gpu', max_length=255, null=True)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
    ]
