# Generated by Django 3.2.13 on 2022-05-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Username', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Password', max_length=255, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('no', models.IntegerField(db_column='No')),
                ('street', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Street', max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='District', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='City', max_length=255, null=True)),
                ('mail', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Mail', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Phone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ccode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='CCode', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Status', max_length=255, null=True)),
                ('member', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Member', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Firstname', max_length=255, null=True)),
                ('midname', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Midname', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Lastname', max_length=255, null=True)),
            ],
            options={
                'db_table': 'fullname',
                'managed': False,
            },
        ),
    ]
