# Generated by Django 3.2.13 on 2022-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('biography', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('language', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('numberofpage', models.IntegerField()),
                ('summary', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('itemcode', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('currentprice', models.FloatField()),
                ('image', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('discount', models.FloatField()),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'bookitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartBookitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemtype', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'cart_bookitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('image', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clothes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothesitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('clothescode', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('currentprice', models.FloatField()),
                ('image', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('discount', models.FloatField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clothesitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Content', max_length=255, null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('rate', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Rate', max_length=255, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Barcode', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Name', max_length=255, null=True)),
                ('warranty', models.IntegerField(db_column='Warranty')),
                ('specification', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Specification', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptopitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('laptopcode', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('currentprice', models.FloatField()),
                ('image', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('discount', models.FloatField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'laptopitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'manufacture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercode', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('createat', models.DateTimeField(blank=True, null=True)),
                ('updateat', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('discount', models.FloatField()),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'producer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'shipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('size', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('color', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('material', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'styles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('screensize', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('gpu', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
    ]
